name: Publish Python Package

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.3.2/install.sh | sh

      - name: Set up Python
        run: uv python install 3.12

      - name: Build
        run: uvx --from build pyproject-build --installer uv

      - name: Publish PyPI
        run: uvx twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
